name: biofuel_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - numpy=1.26.2
  - pandas=2.1.4
  - matplotlib=3.8.2
  - seaborn=0.13.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - networkx=3.2.1
  - geopandas=0.14.1
  - osmnx=1.8.0
  - ipykernel
  - jupyter
  - pip:
      - xgboost==2.0.2
      - traci==1.19.0
      - sumolib==1.19.0
      - lazypredict==0.2.12
      - tqdm==4.66.1
      - shapely==2.0.2
      - folium==0.15.1
      - plotly==6.0.0
